### ISSUE TITLE
SyntaxError : Non ASCII character

### ISSUE THREAD

**Issue by teslaji** [arcticicestudio/igloo#20]
running `./bootstrap` throws such error

> `Traceback (most recent call last):
>   File ".snowsaw/bin/snowsaw", line 13, in <module>
>     import snowsaw
>   File "/home/lucy/igloo/.snowsaw/snowsaw/__init__.py", line 1, in <module>
>     from .cli import main
>   File "/home/lucy/igloo/.snowsaw/snowsaw/cli.py", line 87
> SyntaxError: Non-ASCII character '\xe2' in file /home/lucy/igloo/.snowsaw/snowsaw/cli.py on line 87, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
> `

I tried `nord-gnome-terminal `. it updated the colours and font but no change  in arrows as it shows in first line of your image. figured that it could be encoding issue, hence tried igloo but remained unsolved I hope you can direct me to right direction.

**Comment by arcticicestudio** [comment]
Thanks for your report :+1: 
This looks like a [snowsaw](https://github.com/arcticicestudio/snowsaw) encoding problem. Please subscribe to the moved issue arcticicestudio/snowsaw#20.

Also which Python version and OS are you running?
